# Generated by Django 4.2.17 on 2024-12-23 21:13

import apps.razor_pay.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('txnid', models.CharField(db_index=True, default=apps.razor_pay.models.generate_id, max_length=32)),
                ('basket_id', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('capture_failed', 'Capture Failed'), ('auth_failed', 'Auth Failed')], max_length=32)),
                ('rz_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
